### ISSUE TITLE
Can't generate DRV150 firmware

### ISSUE THREAD

**Issue by tenwx** [scooterhacking/ninebot-es-snsc-firmware-patcher#1]
https://py.scooterhacking.org:81/cfw?version=DRV150&max_speed=33&version_spoofing=on&motor_power_constant=50000&stay_on_locked=on

`
Exception occured:
Traceback (most recent call last):
  File "/root/9botcfw/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/9botcfw/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/9botcfw/web/app.py", line 67, in patch_firmware
    patcher.max_speed(max_speed)
  File "/root/9botcfw/patcher.py", line 156, in max_speed
    ofs = FindPattern(self.data, sig) + 4
  File "/root/9botcfw/patcher.py", line 61, in FindPattern
    while signature[matches] is None or signature[matches] == (data[i + matches] & (mask[matches] if mask else 0xFF)):
IndexError: bytearray index out of range
`

**Comment by scooterhacking** [comment]
As stated on the webpage: 
_Firmware versions marked with (!) might not support patching._

**Comment by scooterhacking** [comment]
DRV150 and DRV151 are now fully supported.
